SELECT
	YEAR(E.DIFFERENTIATION_DATE) as YEAR,
	( 
		SELECT MAX(SIZE_OF_COLONY)
		FROM ECOLI_DATA as sub
		WHERE YEAR(sub.DIFFERENTIATION_DATE) = YEAR(e.DIFFERENTIATION_DATE)
	) - E.SIZE_OF_COLONY as YEAR_DEV,
	E.ID
FROM ECOLI_DATA as E
ORDER BY year, YEAR_DEV;