SELECT FI.ID, FN.FISH_NAME, FI.LENGTH as LENGTH
FROM FISH_INFO as FI
	LEFT JOIN FISH_NAME_INFO AS FN
		on FI.FISH_TYPE = FN.FISH_TYPE
WHERE FI.LENGTH = (
	SELECT MAX(SUB.LENGTH)
	FROM FISH_INFO AS SUB
    WHERE SUB.FISH_TYPE = FI.FISH_TYPE
    )
ORDER BY FI.ID;